img = imread('images/my_img.jpg');
imshow(img);
title("Original Image");
figure;
subplot(2,2,1);
res1 = standard_box(img,3,3);
imshow(res1);
title("3 x 3 image");
subplot(2,2,2);
res2 = standard_box(img,5,5);
imshow(res2);
title("5 x 5 image");
subplot(2,2,3);
res3 = standard_box(img,7,7);
imshow(res3);
title("7 x 7 image");
subplot(2,2,4);
res4 = standard_box(img,9,9);
imshow(res4);
title("9 x 9 image");